import type { Metadata } from "next";
import "../../app/globals.css";
import Header from "../(site)/components/Header";
import BurgerMenu from "../(site)/components/BurgerMenu";

import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-medium-gray min-h-screen  flex justify-center p-10">
      <div
        className="w-fit h-fit p-[10px] md:p-[20px] rounded-3xl mt-10 "
        style={{ backgroundImage: 'url("/texture2.svg")' }}
      >
        <div className={`bg-clear-gray rounded-xl p-5`}>
          <Header></Header>
          <BurgerMenu></BurgerMenu>
          <ToastContainer />
          {children}
        </div>
      </div>
    </div>
  );
}
