import type { Metadata } from "next";
import "../../../app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function IntroLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="bg-medium-gray text-white">{children}</div>;
}
