import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#EFEFED] flex justify-center items-center ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full max-w-6xl min-h-[90vh] rounded-3xl border-frame mt-40">
          {children}
        </div>
      </body>
    </html>
  );
}
