import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Header from "../(site)/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gris-moyen flex justify-center items-center ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="p-[10px] md:p-[20px] rounded-3xl mt-10"
          style={{ backgroundImage: 'url("/texture2.svg")' }}
        >
          <div className={`bg-gris-clair rounded-xl`}>
            <Header></Header>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
